include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    sort_constructors_first: true
    use_super_parameters: true

analyzer:
  errors:
    invalid_annotation_target: ignore
    deprecated_member_use: ignore
    sort_constructors_first: ignore
    sort_child_properties_last: ignore
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
